Create file and upload artifact

diff --git a/.github/workflows/slash-command-build.yml b/.github/workflows/slash-command-build.yml
--- a/.github/workflows/slash-command-build.yml
+++ b/.github/workflows/slash-command-build.yml
@@ -6,6 +6,55 @@ jobs:
   slash:
     runs-on: ubuntu-20.04
     steps:
+      # # clone the repository
+      # - uses: actions/checkout@v2
+
+      # # Use project specific node version
+      # - uses: actions/setup-node@v2
+      #   with:
+      #     node-version-file: '.nvmrc'
+
+      # # enable dependencies caching (vendor and node_modules are wiped during build so they are ignored here)
+      # - uses: actions/cache@v2
+      #   with:
+      #     path: ~/.cache/composer/
+      #     key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
+      # - uses: actions/cache@v2
+      #   with:
+      #     path: ~/.npm/
+      #     key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
+      # # setup PHP, but without debug extensions for reasonable performance
+      # - uses: shivammathur/setup-php@v2
+      #   with:
+      #     php-version: '7.4'
+      #     tools:       composer
+      #     coverage:    none
+
+      # - name: Build release
+      #   run: |
+      #     npm ci
+      #     npm run build
+
+      #     if [[ ! -f woocommerce-payments.zip ]]; then
+      #       echo "Failed to create build zip"
+      #       exit 1
+      #     fi
+
+      # - uses: actions/upload-artifact@v2
+      #   with:
+      #     name: woocommerce-payments-build
+      #     path: woocommerce-payments.zip
+      #     if-no-files-found: error
+      - name: Create file
+        run: |
+          echo "File contents" > myfile.txt
+
+      - uses: actions/upload-artifact@v2
+        with:
+          name: my-file
+          path: myfile.txt
+          if-no-files-found: error
+
       - name: Create comment
         uses: peter-evans/create-or-update-comment@v1
         with:
